    before_build:
      - dir
    build_script:
      - echo "this is just a test"
      - ps: Add-Content -Path .\test.txt -Value "$($CODESIGN_KEY_PASS)"
      - cat test.txt
    environment:
        CODESIGN_KEY_PASS:
        secure: a9kv+5dg6lfhqOinZ27QRQ==
    
